Resources:
  LedgerTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'userId'
          AttributeType: 'S'
        - AttributeName: 'recordId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'userId'
          KeyType: 'HASH'
        - AttributeName: 'recordId'
          KeyType: 'RANGE'
      BillingMode: 'PAY_PER_REQUEST'
      TableName: 'Ledgers'